SexualAssaultFinal/SexualAssaultFinal/Models/EmergencyAgency.cs
namespace SexualAssaultFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("EmergencyAgency")]
    public partial class EmergencyAgency
    {
        [Key]
        public int ea_id { get; set; }

        [StringLength(200)]
        public string ea_name { get; set; }

        [StringLength(500)]
        public string ea_loc { get; set; }

        [StringLength(10)]
        public string ea_postcode { get; set; }

        [StringLength(100)]
        public string ea_contact { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? ea_lat { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? ea_lng { get; set; }
    }
}

SexualAssaultFinal/SexualAssaultFinal/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SexualAssaultFinal.Models;
namespace SexualAssaultFinal.Controllers
{
    public class SupportController : Controller
    {
        Tipmodel db = new Tipmodel();
        EAmodel db1 = new EAmodel();
        // GET: Support        
        public ActionResult LegalTerms()
        {
            ViewBag.Title = "LegalTerms";
            ViewBag.tiplist = db.Tip.ToList();

            return View();
        }
        public ActionResult LegalSupport()
        {
            ViewBag.Title = "LegalSupport";
            return View();
        }
        public ActionResult EmotionalSupport()
        {
            ViewBag.Title = "EmotionalSupport";
            return View();
        }

        public ActionResult EmergencyAgency()
        {
            List<EmergencyAgency> elist = new List<EmergencyAgency>();
            List<EmergencyAgency> storelist = new List<EmergencyAgency>();
            String[] plist = new String[39];
            int count = 0;
            foreach (var item in db1.EmergencyAgency.ToList())
            {
                storelist.Add(item);
                plist[count] = item.ea_postcode;
                count++;
            }
            var result = orderAll(plist);

            for (int i = 37; i >= 0; i--)
            {

                foreach (var item in storelist.ToList())
                {

                    if (result[i].Trim().Equals(item.ea_postcode.Trim()))
                        elist.Add(item);
                }
            }
            ViewBag.emlist = elist.ToList();

            return View();
        }

        public JsonResult sourceToMap()
        {
            return Json(db1.EmergencyAgency.ToList(), JsonRequestBehavior.AllowGet);

        }

        private String[] orderAll(String[] param)
        {
            string temp;
            for (int i = 0; i < 38; i++)
            {
                for (int j = i + 1; j < 38; j++)
                {
                    if (int.Parse(param[i]) < int.Parse(param[j]))
                    {
                        temp = param[i];
                        param[i] = param[j];
                        param[j] = temp;
                    }
                }


                
            }
                  return param;
        }











    }
}

SexualAssaultFinal/SexualAssaultFinal/Views/Support/EmergencyAgency.cshtml
@{
    ViewBag.Title = "EmergencyAgency";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--loading effect-->
<div class="loading justify-content-center align-items-center" id="loading">
    <div class="lds-heart"><div></div></div>
</div>

<link rel="stylesheet" href="@Url.Content("~/css/news.css")">

<style>
    /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
    #map {
        height: 80%;
        width: 100%;
        position: center;
    }
</style>

<!--====================================================
                       Banner
======================================================-->
<div id="home-p" class="home-p pages-hospital text-center">
    <div class="container">
        <h1>Emergency Hospitals 24/7</h1>
        <p>
            @Html.ActionLink("Home", "Index", "Home", new object { }, new { @class = "text-light" }) >> @Html.ActionLink("Hospitals", "EmergencyAgency", "Support", new object { }, new { @class = "text-light" })
        </p>
    </div><!--/end container-->
</div>
<!--====================================================
                       Emergency Hospitals
======================================================-->
<!--====================================================
                       test
======================================================-->
<section id="faq-p1" class="team-p1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="faq-p1-cont">
                    <div class="service-h-tab">
                        <nav class="nav nav-tabs" id="myTab" role="tablist">
                            <a class="nav-item nav-link" href="#tab1" id="stat1-tab" data-toggle="tab" role="tab" aria-controls="stat1" aria-expanded="true">Show with cards</a>
                            <a class="nav-item nav-link" href="#tab2" id="stat2-tab" data-toggle="tab" role="tab" aria-controls="stat2">Show in map</a>
                        </nav>
                        <div class="tab-content" id="nav-tabContent">
                            <!--vis 1-->
                            <div class="tab-pane fade  show active" role="tabpanel" aria-labelledby="stat1-tab" id="tab1">
                                <div class="container">
                                    <div class="row">
                                        @foreach (var item in ViewBag.emlist)
                                        {
                                            <div class="col-md-4">
                                                <div class="card" style="-webkit-transition:none;transition:none;">
                                                    <div class="desc-comp-offer-cont">
                                                        <h3>@item.ea_name</h3>
                                                        <p class="desc"><i class="fa fa-location-arrow"></i>@item.ea_loc</p>
                                                        <p><i class="fa fa-map-pin"></i>@item.ea_postcode</p>
                                                        <p><i class="fa fa-contao"></i>@item.ea_contact</p>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                            <!--vis 2-->
                            <div class="tab-pane fade" role="tabpanel" aria-labelledby="stat2-tab" id="tab2">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1KCHr2_t4vZ6zN2ixD9szpnUemuUcii4&callback=initMap&language=en&callback=initMap&libraries=places"
        async defer></script>
<div id="map"></div>
<script>
    function initMap() {
        var uluru = { lat: -37.813, lng: 144.963 };
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 10,
            center: uluru,
            panControl: true,
            zoomControl: true,
        });
        //get my location

        var locationwindow = new google.maps.InfoWindow({ map: map });
        if (navigator.geolocation)
            navigator.geolocation.getCurrentPosition(function (position) {
                var position = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
                locationwindow.setPosition(position);
                locationwindow.setContent('<p style="color: #ff0000">' + "You are here"+'</p>');

                map.setCenter(position);
                var mylocation = new google.maps.Marker({
                    position: position,
                    map: map,
                    icon: '../img/people.png'
                });

            });
        else
            alert("OOPS! no gelocation support");




        //get agency info from DB
        $.get("@Url.Action("sourceToMap", "Support")", function (result) {

            if (result != undefined)
                {
            $.each(result, function (i, item) {
                addMarker(item.ea_name,item.ea_loc,item.ea_lat,item.ea_lng,item.ea_contact,item.ea_postcode);
            });
            }
        });
        //add marker for agencise
        function addMarker(name, loc, lat, lng, contact, postcode) {
            var urlimage = '../img/hospital.png';
            var newposition = new google.maps.LatLng(lat, lng);
            var marker = new google.maps.Marker({
                position: newposition,
                map: map,
                icon: urlimage
            });
            var contentString =
                '<div class="container">' +
                '<h3>'+ name + '</h3>' +
                '<p>' + "address:" + loc + '</p>' +
                '<p>' + "postcode:" + postcode + '</p>' +
                '<p>' + "phone:" + contact + '</p>' +         
                '</div>';
            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });
            google.maps.event.addListener(marker, 'click', function () {
                infowindow.open(map, marker);
                locationwindow.close();
            });
        }
    }
    google.maps.event.addDomListener(window, "load", initMap);
</script>

<script>
    $(document).ready(function () {
        $("#loading").fadeOut("slow");
    });
</script>














<!--====================================================
                       test
======================================================-->

<section class="container-fluid"></section>

SexualAssaultFinal/SexualAssaultFinal/Views/Support/EmotionalSupport.cshtml
@{
    ViewBag.Title = "EmotionalSupport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="@Url.Content("~/css/services.css")">
<!--====================================================
                       HOME-P
======================================================-->
<div id="home-p" class="home-p pages-head2 text-center">
    <div class="container">
        <h1 class="wow fadeInUp" data-wow-delay="0.1s">Emotional</h1>
        <p>Support</p>
    </div><!--/end container-->
</div>
<!--====================================================
                      Description
======================================================-->
<section id="business-growth-p1" class="business-growth-p1 bg-gray">
    <div class="container">
        <div class="row title-bar">
            <div class="col-md-12">
                <h1 class="wow fadeInUp">We committed to helping</h1>
                <div class="heading-border"></div>
                <p class="wow fadeInUp" data-wow-delay="0.4s">
                    We understand that sexual assault has different emotional impact on different people. We are here to help you in supporting someone you care on their mental well-being. 
                </p>
            </div>
        </div>
        <!--icons-->
        <div class="row wow animated fadeInUp" data-wow-duration="1s" data-wow-delay="0.5s">
            <div class="col-md-3 col-sm-6 service-padding">
                
            </div>
            <div class="col-md-3 col-sm-6 service-padding">
                <div class="service-item" style="cursor:default">
                    <div class="service-item-icon">
                        <i class="fa fa-list-ol fa-3x"></i>
                    </div>
                    <div class="service-item-title">
                        <h3>Tips</h3>
                    </div>
                    <div class="service-item-desc">
                        <p>Few things to remember when providing emotional support to your loved ones.</p>
                        <div class="content-title-underline-light"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 service-padding">
                <div class="service-item" style="cursor:default">
                    <div class="service-item-icon">
                        <i class="fa fa-user-md fa-3x"></i>
                    </div>
                    <div class="service-item-title">
                        <h3>Counselling</h3>
                    </div>
                    <div class="service-item-desc">
                        <p>A wide range of counselling services are available. We will help you find one.</p>
                        <div class="content-title-underline-light"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 service-padding">                
            </div>
        </div>
    </div>
</section>
<!--====================================================
                      Disclaimer
======================================================-->
<section id="financial-p6" class="financial-p6">
    <div class="container">
        <div class="row">            
            <div class="col-md-12">
                <div class="financial-p6-cont">
                    <h2 class="wow fadeInUp">Disclaimer </h2>
                    <div class="heading-border-light"></div>
                    <p>
                        The content on careHer is provided for informative purposes only. No claim is made to the accuracy of the content on this website.
                        The information is provided on the basis that anyone accessing the website is responsible for assessing the accuracy of the information provided.
                    </p>
                    @Html.ActionLink("Read More", "Disclaimer", "Home", new object { }, new { @class = "btn btn-general btn-white" })
                </div>
            </div>
        </div>
    </div>
</section>

SexualAssaultFinal/SexualAssaultFinal/Views/Support/LegalSupport.cshtml
@{
    ViewBag.Title = "LegalSupport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="@Url.Content("~/css/services.css")">
<!--====================================================
                       HOME-P
======================================================-->
<div id="home-p" class="home-p pages-head2 text-center">
    <div class="container">
        <h1 class="wow fadeInUp" data-wow-delay="0.1s">Legal</h1>
        <p>Support</p>
    </div><!--/end container-->
</div>
<!--====================================================
                      Description
======================================================-->
<section id="business-growth-p1" class="business-growth-p1 bg-gray">
    <div class="container">
        <div class="row title-bar">
            <div class="col-md-12">
                <h1 class="wow fadeInUp">We committed to helping</h1>
                <div class="heading-border"></div>
                <p class="wow fadeInUp" data-wow-delay="0.4s">
                    Our team is dedicated to provide information on legal procedures, rights, judiciary law and give access to 
                    relavant agencies and hospitals. 
                </p>
            </div>
        </div>
        <!--icons-->
        <div class="row wow animated fadeInUp" data-wow-duration="1s" data-wow-delay="0.5s">
            <div class="col-md-3 col-sm-6 service-padding">
                <div class="service-item" style="cursor:default">
                    <div class="service-item-icon">
                        <i class="fa fa-tasks fa-3x"></i>
                    </div>
                    <div class="service-item-title">
                        <h3>Procedure</h3>
                    </div>
                    <div class="service-item-desc">
                        <p>We help you understand the legal procedures for reporting your case.</p>
                        <div class="content-title-underline-light"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 service-padding">
                <div class="service-item" style="cursor:default">
                    <div class="service-item-icon">
                        <i class="fa fa-balance-scale fa-3x"></i>
                    </div>
                    <div class="service-item-title">
                        <h3>Rights</h3>
                    </div>
                    <div class="service-item-desc">
                        <p>We can help you find about the rights that a victim is entitled with.</p>
                        <div class="content-title-underline-light"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 service-padding">
                <div class="service-item" style="cursor:default">
                    <div class="service-item-icon">
                        <i class="fa fa-gavel fa-3x"></i>
                    </div>
                    <div class="service-item-title">
                        <h3>Judiciary Law</h3>
                    </div>
                    <div class="service-item-desc">
                        <p>We provide information about judiciary law on the case of sexual assault.</p>
                        <div class="content-title-underline-light"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 service-padding">
                <div class="service-item right-bord" style="cursor:default">
                    <div class="service-item-icon">
                        <i class="fa fa-building-o fa-3x"></i>
                    </div>
                    <div class="service-item-title">
                        <h3>Agencies and Hospitals</h3>
                    </div>
                    <div class="service-item-desc">
                        <p>We list out available agencies and hospitals around your local area.</p>
                        <div class="content-title-underline-light"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--====================================================
                      Disclaimer
======================================================-->
<section id="financial-p6" class="financial-p6">
    <div class="container">
        <div class="row">            
            <div class="col-md-12">
                <div class="financial-p6-cont">
                    <h2 class="wow fadeInUp">Disclaimer </h2>
                    <div class="heading-border-light"></div>
                    <p>
                        The content on careHer is provided for informative purposes only. No claim is made to the accuracy of the content on this website.
                        The information is provided on the basis that anyone accessing the website is responsible for assessing the accuracy of the information provided.
                    </p>                    
                    @Html.ActionLink("Read More", "Disclaimer", "Home", new object { }, new { @class = "btn btn-general btn-white" })
                </div>
            </div>
        </div>
    </div>
</section>

SexualAssaultFinal/SexualAssaultFinal/Views/Support/LegalTerms.cshtml
@{
    ViewBag.Title = "LegalTerms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--loading effect-->
<div class="loading justify-content-center align-items-center" id="loading">
    <div class="lds-heart"><div></div></div>
</div>

<link rel="stylesheet" href="@Url.Content("~/css/faq.css")">
<!--====================================================
                       Banner
======================================================-->
<div id="home-p" class="home-p pages-legalterms text-center">
    <div class="container">
        <h1>Legal Terms</h1>
        <p>
            @Html.ActionLink("Home", "Index", "Home", new object { }, new { @class = "text-light" }) >> @Html.ActionLink("Legal Terms", "LegalTerms", "Support", new object { }, new { @class = "text-light" })
        </p>
    </div><!--/end container-->
</div>
<!--====================================================
                      FAQ-P1
======================================================-->

<section id="faq-p1" class="team-p1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="faq-p1-cont">
                    <div class="service-h-tab">
                        <nav class="nav nav-tabs" id="myTab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-expanded="true">Legal Terms</a>
                        </nav>

                        <div class="tab-content" id="nav-tabContent">
                            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                                @foreach (var item in ViewBag.tiplist)
                                {
                                    <div class="toggle">
                                        <div class="toggle-title ">
                                            <h3>
                                                <i></i>
                                                <span class="title-name">@item.T_question</span>
                                            </h3>
                                        </div>
                                        <div class="toggle-inner">
                                            <p>@item.T_answer</p>
                                        </div>
                                    </div>

                                }
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    if (jQuery(".toggle .toggle-title").hasClass('active')) {
        jQuery(".toggle .toggle-title.active").closest('.toggle').find('.toggle-inner').show();
    }
    jQuery(".toggle .toggle-title").click(function () {
        if (jQuery(this).hasClass('active')) {
            jQuery(this).removeClass("active").closest('.toggle').find('.toggle-inner').slideUp(200);
        }
        else {
            jQuery(this).addClass("active").closest('.toggle').find('.toggle-inner').slideDown(200);
        }
    });
</script>

<script>
    $(document).ready(function () {
        $("#loading").fadeOut("slow");
    });
</script>